stages:
  - build_docker_images
  - deploy
  - test

build_ubuntu20:
  stage: build_docker_images

  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/ubuntu20:latest

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $IMAGE_NAME || true
    - docker build --cache-from $IMAGE_NAME --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

