name: Zeek Stable w/ Ubuntu 20

job:
  test_ubuntu_20:
    name: Zeek Stable w/ Ubuntu 20
    runs-on: ubuntu-20.04

    on: [push, pull_request]

    steps:
      - name: Install dependencies
        run: apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python3 python3-dev python3-git python3-semantic-version swig zlib1g-dev

      - name: Checkout Zeek repo
        uses: actions/checkout@v1
        repository: zeek/zeek
        ref: release
        with:
          submodules: recursive

      - name: Configure Zeek
        run: ./configure
        working-directory: ./zeek

      - name: Build Zeek
        run: make
        working-directory: ./zeek

      - name: Install Zeek
        run: make install
        working-directory: ./zeek
