name: Zeek Stable w/ Ubuntu 20

on: [push, pull_request]

jobs:
  test_ubuntu_20:
    name: Zeek Stable w/ Ubuntu 20
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: sudo apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python3 python3-dev python3-git python3-semantic-version swig zlib1g-dev

      - name: Checkout Zeek repo
        uses: actions/checkout@v1
        with:
          submodules: recursive
          repository: zeek/zeek
          ref: release

      - name: Configure Zeek
        run: ./configure --prefix=/usr/local
        working-directory: ../zeek

      - name: Build Zeek
        run: make -j4
        working-directory: ../zeek

      - name: Install Zeek
        run: sudo make install
        working-directory: ../zeek

      - name: Checkout Plugin repo
        uses: actions/checkout@v1

      - name: Install DPDK prereqs
        run: sudo apt install -y dpdk dpdk-igb-uio-dkms linux-headers-$(uname -r)

      - name: Install DPDK
        run: sudo zkg install --force ./dpdk-plugin
